services:
  sapphire-localnet:
    image: ghcr.io/oasisprotocol/sapphire-localnet
    container_name: sapphire-localnet
    ports:
      # Map all required ports (RPC, WebSocket, Explorer)
      - "8544:8544"
      - "8545:8545"
      - "8546:8546"
      - "8547:8547"
      - "8548:8548"
    volumes:
      # Optional: Persist blockchain data between restarts
      - ./localnet-data:/data
      # Mount logs directory to host for easier access
      - ./logs:/logs
    environment:
      OASIS_NODE_LOG_LEVEL: debug
      LOG__LEVEL: debug
      # Ensure logs are written to both console and files
      LOG__FILE: "/logs/sapphire-node.log"
      LOG__FILE_LEVEL: debug
      # Optional environment variables to configure the node
#      - SAPPHIRE_CHAINID=9000
#      - MINING_PERIOD=1
    restart: unless-stopped
    # For debugging
    tty: true
    stdin_open: true
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"